### ISSUE TITLE
Adapt ScispaCy to create JSON ISentence objects

### ISSUE THREAD

**Issue by KnowledgeGarden** [KnowledgeGarden/SimpleOpenSherlock#2]
This is an important first step. Right now, ScispaCy has been shown to read a collection of sentences and paragraphs from early OpenSherlock tests. It can:
* Break paragraphs into sentences
* Detect entities in the entire paragraph
* Detect noun chunks in the entire paragraph
* Return POS tuples for each sentence
What remains is to be able to
* add entities to the IDocument it is processing
* add noun chunks to the IDocument it is processing
* for each sentence, create an ISentence JSONobject
* include in it the sentence itself
* include also the POS tuples

**Comment by KnowledgeGarden** [comment]
Python's JSON handling is simple and crude, and far more effort than it is worth.<br/>
I am considering just sending paragraphs to ScispaCy  and getting back text blobs which are line oriented, with, e.g. a tag (sentence: ) followed by the object.

**Comment by KnowledgeGarden** [comment]
In a sense, this simplifies what ScispaCy does, but it means that tqos-asr-documizer must be returned to its earlier state of full processing of IDocuments down to paragraphs and sentences.<br/>
We then just begin passing sentences to ScispaCy agents and dealingi with what comes back.

**Comment by maparent** [comment]
Python's json handling is just fine if you know how to you're doing.

**Comment by KnowledgeGarden** [comment]
After that experience, I am beginning to think it's faster to just let Documizer do the background work and just let spacy do what it does best.

**Comment by KnowledgeGarden** [comment]
ScispaCy now creates JSON sentence objects, with thanks to Marc-Antoine for coding hints.

**Comment by KnowledgeGarden** [comment]
Closed too soon. It makes JSON from a parse; must now be rewritten to work in the larger environment of IDocument JSON; then it can be closed.<br/>
Next steps, really, include creating a python Class which takes a JSON IDocument object and processes it down to the collection of ISentence objects.

**Comment by KnowledgeGarden** [comment]
Actually, the decision was made today to not create ISentence Objects. So, we will create a new Issue for what is planned.
